services:

  clickhouse:

    image: clickhouse/clickhouse-server:24.3

    container_name: clickhouse

    ports:
      - "8123:8123"
      - "9000:9000"

    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123

    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      retries: 10

  generator:

    build: ./generator

    depends_on:
      clickhouse:
        condition: service_healthy

    restart: always

  airflow:

    build: ./airflow

    container_name: airflow

    depends_on:
      clickhouse:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:

      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname admin
      --lastname admin
      --role Admin
      --email admin@test.com || true &&
      airflow standalone
      "

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark:/opt/spark 

  spark-master:
    build: ./spark
    container_name: spark-master

    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080

    ports:
      - "7077:7077"
      - "8081:8080"

    environment:
      - SPARK_MODE=master

    volumes:
      - ./spark/work-dir:/opt/spark/work-dir

  # =========================
  # SPARK WORKERS
  # =========================
  spark-worker-1:
    build: ./spark    
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077

    volumes:
      - ./spark/work-dir:/opt/spark/work-dir

  spark-worker-2:
    build: ./spark
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077

    volumes:
      - ./spark/work-dir:/opt/spark/work-dir

  spark-worker-3:
    build: ./spark
    container_name: spark-worker-3
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - ./spark/work-dir:/opt/spark/work-dir
